[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "ipython>=8.18.1",
    "matplotlib>=3.9.4",
    "matplotlib-inline>=0.2.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
